export const AddonsData = [
  {
    id: "1",
    Addon: "Free",
    image: "addon-01.svg",
    price: "$10",
    Type: "	Softner",
    Status: "Active",
    Actions: "",
  },
  {
    id: "2",
    Addon: "Free",
    image: "addon-05.svg",
    price: "$10",
    Type: "Detergent",
    Status: "Active",
    Actions: "",
  },
  {
    id: "3",
    Addon: "Hang Dry",
    image: "addon-09.svg",
    price: "$1",
    Type: "	Dry",
    Status: "Active",
    Actions: "",
  },
  {
    id: "4",
    Addon: "High Hot",
    image: "addon-06.svg",
    price: "$8",
    Type: "Dry",
    Status: "Active",
    Actions: "",
  },
  {
    id: "5",
    Addon: "Low Heat",
    image: "addon-07.svg",
    price: "$6",
    Type: "	Dry",
    Status: "Active",
    Actions: "",
  },
  {
    id: "6",
    Addon: "No Detergent",
    image: "addon-04.svg",
    price: "-",
    Type: "Detergent",
    Status: "Inactive",
    Actions: "",
  },
  {
    id: "7",
    Addon: "No Softener",
    image: "addon-03.svg",
    price: "$22",
    Type: "Softner",
    Status: "Active",
    Actions: "",
  },
  {
    id: "8",
    Addon: "Premium",
    image: "addon-02.svg",
    price: "$0",
    Type: "Softner",
    Status: "Active",
    Actions: "",
  },
  {
    id: "9",
    Addon: "Premium",
    image: "addon-08.svg",
    price: "$4",
    Type: "Detergent",
    Status: "Active",
    Actions: "",
  },
];
