export const CustomerReportData = [
  {
    id: "1",
    Order_ID: "#CUS0016",
    Customer: "Julie Kangas",
    image: "avatar-10.jpg",
    Items: "14",
    Amount: "	$30.40",
    Payment_Method: "Cash",
  },
  {
    id: "2",
    Order_ID: "#CUS0015",
    Customer: "David Belcher",
    image: "avatar-09.jpg",
    Items: "16",
    Amount: "$32.10",
    Payment_Method: "Cash",
  },
  {
    id: "3",
    Order_ID: "#CUS0014",
    Customer: "Andrea Aponte",
    image: "avatar-08.jpg",
    Items: "19",
    Amount: "$72.60",
    Payment_Method: "Credit Card",
  },
  {
    id: "4",
    Order_ID: "#CUS0013",
    Customer: "Ron Jude",
    image: "avatar-07.jpg",
    Items: "8",
    Amount: "$45.30",
    Payment_Method: "Cash",
  },
  {
    id: "5",
    Order_ID: "#CUS0012",
    Customer: "Nancy Chapman",
    image: "avatar-06.jpg",
    Items: "16",
    Amount: "$57.20",
    Payment_Method: "	PayPal",
  },
  {
    id: "6",
    Order_ID: "#CUS0011",
    Customer: "Jim Vickers",
    image: "avatar-05.jpg",
    Items: "14",
    Amount: "$61.40",
    Payment_Method: "	Cash",
  },
  {
    id: "7",
    Order_ID: "#CUS0010",
    Customer: "Kelley Davis",
    image: "avatar-04.jpg",
    Items: "12",
    Amount: "$92.80",
    Payment_Method: "Credit Card",
  },
  {
    id: "8",
    Order_ID: "#CUS0009",
    Customer: "Frank Barrett",
    image: "avatar-03.jpg",
    Items: "16",
    Amount: "$45.10",
    Payment_Method: "	PayPal",
  },
  {
    id: "9",
    Order_ID: "#CUS0008",
    Customer: "Sue Allen",
    image: "avatar-02.jpg",
    Items: "12",
    Amount: "$78.20",
    Payment_Method: "	Cash",
  },
  {
    id: "10",
    Order_ID: "#CUS0007",
    Customer: "Adrian James",
    image: "avatar-01.jpg",
    Items: "24",
    Amount: "$34.50",
    Payment_Method: "Credit Card",
  },
];
