export const DriversListData = [
  {
    id: "1",
    Driver: "Alex Campbell",
    image: "driver-09.jpg",
    email: "alex@example.com",
    mobile: "+1 14524 54595",
    Status: "Active",
    Actions: "",
  },
  {
    id: "2",
    Driver: "Avery Parker",
    image: "driver-05.jpg",
    email: "avery@example.com",
    mobile: "+1 58974 54591",
    Status: "Active",
    Actions: "",
  },
  {
    id: "3",
    Driver: "Benjamin Scott",
    image: "driver-01.jpg",
    email: "benjamin@example.com",
    mobile: "+1 58544 78987",
    Status: "Active",
    Actions: "",
  },
  {
    id: "4",
    Driver: "Cameron Lee",
    image: "driver-07.jpg",
    email: "cameron@example.com",
    mobile: "+1 31245 54593",
    Status: "Active",
    Actions: "",
  },
  {
    id: "5",
    Driver: "Casey Adams",
    image: "driver-10.jpg",
    email: "casey@example.com",
    mobile: "+1 22145 54596",
    Status: "Active",
    Actions: "",
  },
  {
    id: "6",
    Driver: "Jamie Brooks",
    image: "driver-08.jpg",
    email: "jamie@example.com",
    mobile: "+1 47854 54594",
    Status: "Active",
    Actions: "",
  },
  {
    id: "7",
    Driver: "Matthew Parker",
    image: "driver-02.jpg",
    email: "mat@example.com",
    mobile: "+1 45478 54588",
    Status: "Active",
    Actions: "",
  },
  {
    id: "8",
    Driver: "Quinn Bailey",
    image: "driver-06.jpg",
    email: "quinn@example.com",
    mobile: "+1 96587 54592",
    Status: "Active",
    Actions: "",
  },
  {
    id: "9",
    Driver: "Riley Cooper",
    image: "driver-04.jpg",
    email: "riley@example.com",
    mobile: "+1 47854 54590",
    Status: "Inactive",
    Actions: "",
  },
  {
    id: "10",
    Driver: "Samuel Harris",
    image: "driver-03.jpg",
    email: "sam@example.com",
    mobile: "+1 33658 54589",
    Status: "Active",
    Actions: "",
  },
];
