export const EarningsReportData = [
  {
    id: "1",
    Invoice_ID: "#ERN0016",
    Customer: "Julie Kangas",
    image: "avatar-10.jpg",
    Order_ID: "OD6564",
    Amount: "	$30.40",
    Date: "30 Aug 2025",
    Payment_Method: "Cash",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "2",
    Invoice_ID: "#ERN0015",
    Customer: "David Belcher",
    image: "avatar-09.jpg",
    Order_ID: "OD4567",
    Amount: "$32.10",
    Date: "	11 Aug 2025",
    Payment_Method: "Cash",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "3",
    Invoice_ID: "#ERN0014",
    Customer: "Andrea Aponte",
    image: "avatar-08.jpg",
    Order_ID: "OD0123",
    Amount: "$72.60",
    Date: "	22 Aug 2025",
    Payment_Method: "Credit Card",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "4",
    Invoice_ID: "#ERN0013",
    Customer: "Ron Jude",
    image: "avatar-07.jpg",
    Order_ID: "OD6789",
    Amount: "$45.30",
    Date: "07 Sep 2025",
    Payment_Method: "Cash",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "5",
    Invoice_ID: "#ERN0012",
    Customer: "Nancy Chapman",
    image: "avatar-06.jpg",
    Order_ID: "OD1357",
    Amount: "$57.20",
    Date: "	15 Sep 2025",
    Payment_Method: "	PayPal",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "6",
    Invoice_ID: "#ERN0011",
    Customer: "Jim Vickers",
    image: "avatar-05.jpg",
    Order_ID: "OD7890",
    Amount: "$61.40",
    Date: "29 Sep 2025",
    Payment_Method: "	Cash",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "7",
    Invoice_ID: "#ERN0010",
    Customer: "Kelley Davis",
    image: "avatar-04.jpg",
    Order_ID: "	OD3456",
    Amount: "$92.80",
    Date: "	18 Oct 2025",
    Payment_Method: "Credit Card",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "8",
    Invoice_ID: "#ERN0009",
    Customer: "Frank Barrett",
    image: "avatar-03.jpg",
    Order_ID: "OD9012",
    Amount: "$45.10",
    Date: "03 Nov 2025",
    Payment_Method: "	PayPal",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "9",
    Invoice_ID: "#ERN0008",
    Customer: "Sue Allen",
    image: "avatar-02.jpg",
    Order_ID: "OD5678",
    Amount: "$78.20",
    Date: "12 Nov 2025",
    Payment_Method: "	Cash",
    Status: "Completed",
    Actions: "",
  },
  {
    id: "10",
    Invoice_ID: "#ERN0007",
    Customer: "Adrian James",
    image: "avatar-01.jpg",
    Order_ID: "OD1245",
    Amount: "$34.50",
    Date: "25 Dec 2025",
    Payment_Method: "Credit Card",
    Status: "Completed",
    Actions: "",
  },
];
