export const InvoicesData = [
  {
    id: "1",
    Invoice_ID: "#INV0016",
    Customer: "Julie Kangas",
    image: "avatar-10.jpg",
    Amount: "$4108",
    Date: "30 Aug 2025",
    Payment_Method: "Cash",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "2",
    Invoice_ID: "#INV0015",
    Customer: "David Belcher",
    image: "avatar-09.jpg",
    Amount: "$3136",
    Date: "	11 Aug 2025",
    Payment_Method: "Cash",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "3",
    Invoice_ID: "#INV0014",
    Customer: "Andrea Aponte",
    image: "avatar-08.jpg",
    Amount: "$4178",
    Date: "	22 Aug 2025",
    Payment_Method: "Credit Card",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "4",
    Invoice_ID: "#INV0013",
    Customer: "Ron Jude",
    image: "avatar-07.jpg",
    Amount: "$3665",
    Date: "07 Sep 2025",
    Payment_Method: "Cash",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "5",
    Invoice_ID: "#INV0012",
    Customer: "Nancy Chapman",
    image: "avatar-06.jpg",
    Amount: "$3160",
    Date: "	15 Sep 2025",
    Payment_Method: "	PayPal",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "6",
    Invoice_ID: "#INV0011",
    Customer: "Jim Vickers",
    image: "avatar-05.jpg",
    Amount: "$3620",
    Date: "29 Sep 2025",
    Payment_Method: "	Cash",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "7",
    Invoice_ID: "#INV0010",
    Customer: "Kelley Davis",
    image: "avatar-04.jpg",
    Amount: "$4558",
    Date: "	18 Oct 2025",
    Payment_Method: "Credit Card",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "8",
    Invoice_ID: "#INV0009",
    Customer: "Frank Barrett",
    image: "avatar-03.jpg",
    Amount: "$9465",
    Date: "03 Nov 2025",
    Payment_Method: "	PayPal",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "9",
    Invoice_ID: "#INV0008",
    Customer: "Sue Allen",
    image: "avatar-02.jpg",
    Amount: "$4420",
    Date: "12 Nov 2025",
    Payment_Method: "	Cash",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "10",
    Invoice_ID: "#INV0007",
    Customer: "Adrian James",
    image: "avatar-01.jpg",
    Amount: "$3150",
    Date: "25 Dec 2025",
    Payment_Method: "Credit Card",
    Status: "Paid",
    Actions: "",
  },
];
