export const OrdersReportData = [
  {
    id: "1",
    Order_ID: "OD0123",
    Customer: "Andrea Aponte",
    image: "avatar-08.jpg",
    Items: "19",
    Amount: "	$30.40",
    Date: "30 Aug 2025",
    Payment_Method: "Credit Card",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "2",
    Order_ID: "OD1245",
    Customer: "Adrian James",
    image: "avatar-01.jpg",
    Items: "24",
    Amount: "$32.10",
    Date: "	11 Aug 2025",
    Payment_Method: "Credit Card",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "3",
    Order_ID: "OD1357",
    Customer: "David Belcher",
    image: "avatar-09.jpg",
    Items: "16",
    Amount: "$72.60",
    Date: "	22 Aug 2025",
    Payment_Method: "Cash",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "4",
    Order_ID: "OD2345",
    Customer: "Nancy Chapman",
    image: "avatar-06.jpg",
    Items: "12",
    Amount: "$45.30",
    Date: "07 Sep 2025",
    Payment_Method: "Paypal",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "5",
    Order_ID: "OD3456",
    Customer: "Kelley Davis",
    image: "avatar-04.jpg",
    Items: "14",
    Amount: "$57.20",
    Date: "	15 Sep 2025",
    Payment_Method: "Credit Card",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "6",
    Order_ID: "OD5678",
    Customer: "Sue Allen",
    image: "avatar-02.jpg",
    Items: "8",
    Amount: "$61.40",
    Date: "29 Sep 2025",
    Payment_Method: "Cash",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "7",
    Order_ID: "OD6564",
    Customer: "Julie Kangas",
    image: "avatar-10.jpg",
    Items: "14",
    Amount: "$92.80",
    Date: "	18 Oct 2025",
    Payment_Method: "Credit Card",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "8",
    Order_ID: "OD6789",
    Customer: "Ron Jude",
    image: "avatar-07.jpg",
    Items: "10",
    Amount: "$45.10",
    Date: "03 Nov 2025",
    Payment_Method: "PayPal",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "9",
    Order_ID: "OD7890",
    Customer: "Jim Vickers",
    image: "avatar-05.jpg",
    Items: "16",
    Amount: "$78.20",
    Date: "12 Nov 2025",
    Payment_Method: "Cash",
    Status: "Paid",
    Actions: "",
  },
  {
    id: "10",
    Order_ID: "OD9012",
    Customer: "Frank Barrett",
    image: "avatar-03.jpg",
    Items: "14",
    Amount: "$34.50",
    Date: "25 Dec 2025",
    Payment_Method: "Credit Card",
    Status: "Cancelled",
    Actions: "",
  },
];
