export const ProductsData = [
  {
    id: "1",
    product: "Blouse",
    image: "product-03.svg",
    serivce: "Clothing, Ironing",
    category: "Dresses",
    price: "$38",
    Status: "Active",
    Actions: "",
  },
  {
    id: "2",
    product: "Blouse Iron Only",
    image: "product-04.svg",
    serivce: "Laundry, Wet Cleaning",
    category: "Suits",
    price: "$33",
    Status: "Active",
    Actions: "",
  },
  {
    id: "3",
    product: "Dress Shorten",
    image: "product-09.svg",
    serivce: "Clothing",
    category: "Dresses",
    price: "$12",
    Status: "Active",
    Actions: "",
  },
  {
    id: "4",
    product: "Dress with Trims",
    image: "product-06.svg",
    serivce: "Laundry, Wash & Iron",
    category: "Knitwear",
    price: "$36",
    Status: "Active",
    Actions: "",
  },
  {
    id: "5",
    product: "Evening Dress",
    image: "product-02.svg",
    serivce: "Laundry, Wet Cleaning, Wash & Iron +3",
    category: "Dresses",
    price: "$49",
    Status: "Active",
    Actions: "",
  },
  {
    id: "6",
    product: "Jumpsuit",
    image: "product-08.svg",
    serivce: "Clothing",
    category: "Dresses",
    price: "$65",
    Status: "Active",
    Actions: "",
  },
  {
    id: "7",
    product: "Shirt",
    image: "product-07.svg",
    serivce: "Laundry, Ironing",
    category: "Dresses",
    price: "$24",
    Status: "Inactive",
    Actions: "",
  },
  {
    id: "8",
    product: "Silk Blouse",
    image: "product-04.svg",
    serivce: "Clothing",
    category: "Dresses",
    price: "$24",
    Status: "Active",
    Actions: "",
  },
  {
    id: "9",
    product: "Silk Skirt",
    image: "product-05.svg",
    serivce: "Dry Cleaning, Ironing",
    category: "Knitwear",
    price: "$46",
    Status: "Active",
    Actions: "",
  },
  {
    id: "10",
    product: "Waistcoat",
    image: "product-01.svg",
    serivce: "Dry Cleaning, Ironing",
    category: "Accessories",
    price: "$25",
    Status: "Active",
    Actions: "",
  },
];
