export const SalesReportData = [
  {
    id: "1",
    Sales_ID: "#SA00016",
    Category: "Bed Sets",
    Items: "24",
    Total_Orders: "24",
    Amount: "	$30.40",
    Date: "30 Aug 2025",
    Payment_Method: "Cash",
    Status: "Completed",
  },
  {
    id: "2",
    Sales_ID: "#SA00015",
    Category: "Bedding",
    Items: "14",
    Total_Orders: "14",
    Amount: "$32.10",
    Date: "	11 Aug 2025",
    Payment_Method: "Cash",
    Status: "Completed",
  },
  {
    id: "3",
    Sales_ID: "#SA00014",
    Category: "Knitwear",
    Items: "16",
    Total_Orders: "16",
    Amount: "$72.60",
    Date: "	22 Aug 2025",
    Payment_Method: "Credit Card",
    Status: "Completed",
  },
  {
    id: "4",
    Sales_ID: "#SA00013",
    Category: "Suits",
    Items: "14",
    Total_Orders: "14",
    Amount: "$45.30",
    Date: "07 Sep 2025",
    Payment_Method: "Cash",
    Status: "Completed",
  },
  {
    id: "5",
    Sales_ID: "#SA00012",
    Category: "Jackets",
    Items: "16",
    Total_Orders: "16",
    Amount: "$57.20",
    Date: "	15 Sep 2025",
    Payment_Method: "	PayPal",
    Status: "Completed",
  },
  {
    id: "6",
    Sales_ID: "#SA00011",
    Category: "Coats",
    Items: "12",
    Total_Orders: "12",
    Amount: "$61.40",
    Date: "29 Sep 2025",
    Payment_Method: "	Cash",
    Status: "Completed",
  },
  {
    id: "7",
    Sales_ID: "#SA00010",
    Category: "Ironed and hung",
    Items: "16",
    Total_Orders: "16",
    Amount: "$92.80",
    Date: "	18 Oct 2025",
    Payment_Method: "Credit Card",
    Status: "Completed",
  },
  {
    id: "8",
    Sales_ID: "#SA00009",
    Category: "Dresses",
    Items: "19",
    Total_Orders: "19",
    Amount: "$45.10",
    Date: "03 Nov 2025",
    Payment_Method: "	PayPal",
    Status: "Completed",
  },
  {
    id: "9",
    Sales_ID: "#SA00008",
    Category: "Scarf",
    Items: "12",
    Total_Orders: "12",
    Amount: "$78.20",
    Date: "12 Nov 2025",
    Payment_Method: "	Cash",
    Status: "Completed",
  },
  {
    id: "10",
    Sales_ID: "#SA00007",
    Category: "Accessories",
    Items: "8",
    Total_Orders: "8",
    Amount: "$34.50",
    Date: "25 Dec 2025",
    Payment_Method: "Credit Card",
    Status: "Completed",
  },
];
