export const StaffListData = [
  {
    id: "1",
    staff: "Aiden Murphy",
    image: "staff-08.jpg",
    Role: "Supervisor",
    mobile: "+1 65454 75394",
    Status: "Active",
    Actions: "",
  },
  {
    id: "2",
    staff: "Charlotte Evans",
    image: "staff-07.jpg",
    Role: "Removal Expert",
    mobile: "+1 32145 15993",
    Status: "Active",
    Actions: "",
  },
  {
    id: "3",
    staff: "David Harris",
    image: "staff-09.jpg",
    Role: "Branch Manager",
    mobile: "+1 98724 84695",
    Status: "Active",
    Actions: "",
  },
  {
    id: "4",
    staff: "Hannah Lewis",
    image: "staff-06.jpg",
    Role: "Ironing Staff",
    mobile: "+1 78987 36992",
    Status: "Active",
    Actions: "",
  },
  {
    id: "5",
    staff: "Jason Miller",
    image: "staff-01.jpg",
    Role: "Admin",
    mobile: "+1 58544 78987",
    Status: "Active",
    Actions: "",
  },
  {
    id: "6",
    staff: "Michael Roberts",
    image: "staff-03.jpg",
    Role: "Attendant",
    mobile: "+1 65458 96389",
    Status: "Active",
    Actions: "",
  },
  {
    id: "7",
    staff: "Micheal Stewart",
    image: "staff-10.jpg",
    Role: "Technician",
    mobile: "+1 25845 95196",
    Status: "Active",
    Actions: "",
  },
  {
    id: "8",
    staff: "Olivia Carter",
    image: "staff-04.jpg",
    Role: "Operator",
    mobile: "+1 12354 74190",
    Status: "Inactive",
    Actions: "",
  },
  {
    id: "9",
    staff: "Sarah Thompson",
    image: "staff-02.jpg",
    Role: "Biller",
    mobile: "	+1 98778 12388",
    Status: "Active",
    Actions: "",
  },
  {
    id: "10",
    staff: "Sophia Hayes",
    image: "staff-05.jpg",
    Role: "Dryer Operator",
    mobile: "+1 45674 85291",
    Status: "Active",
    Actions: "",
  },
];
