// Re-export POS components from src/components/pos/
export { default as PosTable } from '@/components/pos/pos-table'
export { default as PosTableCard } from '@/components/pos/pos-table-card'
export { default as PosTablePagination } from '@/components/pos/pos-table-pagination'
export { default as PosFormModal } from '@/components/pos/pos-form-modal'
export { default as PosPageHeader } from '@/components/pos/pos-page-header'
export { default as PosPageActions } from '@/components/pos/pos-page-actions'
export { default as PosTableToolbar } from '@/components/pos/pos-table-toolbar'
export { default as PosTableStatus } from '@/components/pos/pos-table-status'
export * from '@/components/pos/pos-colors'
