import { Router } from 'express';
import { register as r0 } from '../../../controllers/discussions/groupDms/route-00.js';
import { register as r1 } from '../../../controllers/discussions/groupDms/route-01.js';
import { register as r2 } from '../../../controllers/discussions/groupDms/route-02.js';
import { register as r3 } from '../../../controllers/discussions/groupDms/route-03.js';
import { register as r4 } from '../../../controllers/discussions/groupDms/route-04.js';
import { register as r5 } from '../../../controllers/discussions/groupDms/route-05.js';
import { register as r6 } from '../../../controllers/discussions/groupDms/route-06.js';
import { register as r7 } from '../../../controllers/discussions/groupDms/route-07.js';
import { register as r8 } from '../../../controllers/discussions/groupDms/route-08.js';
import { register as r9 } from '../../../controllers/discussions/groupDms/route-09.js';
import { register as r10 } from '../../../controllers/discussions/groupDms/route-10.js';
import { register as r11 } from '../../../controllers/discussions/groupDms/route-11.js';
import { register as r12 } from '../../../controllers/discussions/groupDms/route-12.js';
import { register as r13 } from '../../../controllers/discussions/groupDms/route-13.js';

const router = Router();
r0(router);
r1(router);
r2(router);
r3(router);
r4(router);
r5(router);
r6(router);
r7(router);
r8(router);
r9(router);
r10(router);
r11(router);
r12(router);
r13(router);

export default router;
