'use client';

import type { PlatformAnalytics } from '@/features/admin/api/admin-api';
import type { ReportCatalogItem } from '@/features/admin/components/admin-reports/export-reports';
import { Badge } from '@/components/ui/badge';
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from '@/components/ui/sheet';
import { Separator } from '@/components/ui/separator';
import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';

export function ReportDetailSheet({
  report,
  data,
  open,
  onOpenChange,
}: {
  report: ReportCatalogItem | null;
  data?: PlatformAnalytics;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  if (!report || !data) return null;

  const metrics = [
    { label: 'Total users', value: data.kpis.totalUsers },
    { label: 'Active this month', value: data.kpis.activeUsersThisMonth },
    { label: 'Courses', value: data.kpis.totalCourses },
    { label: 'Quiz attempts', value: data.kpis.quizAttempts },
    { label: 'Completion rate', value: `${data.kpis.completionRate}%` },
    { label: 'Pass rate', value: `${data.kpis.quizPassRate}%` },
  ];

  const chartData = data.charts.userGrowth.slice(-6);

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className='w-full overflow-y-auto sm:max-w-xl'>
        <SheetHeader>
          <SheetTitle>{report.name}</SheetTitle>
          <SheetDescription>{report.description}</SheetDescription>
        </SheetHeader>

        <div className='mt-6 space-y-6'>
          <section className='space-y-2'>
            <h3 className='text-sm font-semibold'>Summary</h3>
            <div className='grid gap-2 text-sm'>
              <div className='flex justify-between gap-4'>
                <span className='text-muted-foreground'>Period</span>
                <span>{data.scope.periodLabel}</span>
              </div>
              <div className='flex justify-between gap-4'>
                <span className='text-muted-foreground'>Scope</span>
                <span>{data.scope.facultyName ?? 'All faculties'}</span>
              </div>
              <div className='flex justify-between gap-4'>
                <span className='text-muted-foreground'>Category</span>
                <Badge variant='outline'>{report.category}</Badge>
              </div>
              <div className='flex justify-between gap-4'>
                <span className='text-muted-foreground'>Generated by</span>
                <span>System</span>
              </div>
            </div>
          </section>

          <Separator />

          <section className='space-y-3'>
            <h3 className='text-sm font-semibold'>Key metrics</h3>
            <div className='grid grid-cols-2 gap-2'>
              {metrics.map((m) => (
                <div key={m.label} className='rounded-xl border bg-muted/30 p-3'>
                  <p className='text-muted-foreground text-xs'>{m.label}</p>
                  <p className='text-lg font-semibold tabular-nums'>{m.value}</p>
                </div>
              ))}
            </div>
          </section>

          <Separator />

          <section className='space-y-3'>
            <h3 className='text-sm font-semibold'>Visualizations</h3>
            <div className='rounded-xl border p-3'>
              <p className='text-muted-foreground mb-2 text-xs'>User growth</p>
              <ResponsiveContainer width='100%' height={180}>
                <BarChart data={chartData}>
                  <CartesianGrid strokeDasharray='3 3' className='stroke-border/50' />
                  <XAxis dataKey='month' tick={{ fontSize: 10 }} />
                  <YAxis tick={{ fontSize: 10 }} width={28} />
                  <Tooltip />
                  <Bar dataKey='users' fill='hsl(var(--primary))' radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </section>

          <Separator />

          <section className='space-y-2'>
            <h3 className='text-sm font-semibold'>Insights</h3>
            <ul className='space-y-2'>
              {data.insights.map((line) => (
                <li
                  key={line}
                  className='rounded-xl border border-amber-200/60 bg-amber-50/50 px-3 py-2 text-sm dark:border-amber-900/40 dark:bg-amber-950/20'
                >
                  {line}
                </li>
              ))}
            </ul>
          </section>
        </div>
      </SheetContent>
    </Sheet>
  );
}
