/**
 * Permission bit definitions. Keep stable: persisted in `allow`/`deny` rows
 * and in pre-seeded `DiscussionRole.permissions` masks.
 */
export const PERMISSION_BITS = Object.freeze({
  VIEW_CHANNEL: 1n << 0n,
  READ_MESSAGE_HISTORY: 1n << 1n,
  SEND_MESSAGES: 1n << 2n,
  ATTACH_FILES: 1n << 3n,
  EMBED_LINKS: 1n << 4n,
  ADD_REACTIONS: 1n << 5n,
  USE_EXTERNAL_EMOJI: 1n << 6n,
  MENTION_EVERYONE: 1n << 7n,
  CREATE_THREADS: 1n << 8n,
  SEND_MESSAGES_IN_THREADS: 1n << 9n,
  MANAGE_MESSAGES: 1n << 10n,
  MANAGE_THREADS: 1n << 11n,
  PIN_MESSAGES: 1n << 12n,
  MANAGE_CHANNEL: 1n << 13n,
  MANAGE_ROLES: 1n << 14n,
  MANAGE_SERVER: 1n << 15n,
  KICK_MEMBERS: 1n << 16n,
  BAN_MEMBERS: 1n << 17n,
  CREATE_INVITE: 1n << 18n,
  VIEW_AUDIT_LOG: 1n << 19n,
  MANAGE_EMOJI: 1n << 20n,
  MUTE_MEMBERS: 1n << 21n,
  MODERATE_MEMBERS: 1n << 22n,
});

/** When set, all permission checks pass. */
export const PERMISSION_ADMINISTRATOR = 1n << 31n;

export const PERMISSION_ALL = (() => {
  let all = PERMISSION_ADMINISTRATOR;
  for (const bit of Object.values(PERMISSION_BITS)) all |= bit;
  return all;
})();

const B = PERMISSION_BITS;

export const SYSTEM_ROLE_KEYS = Object.freeze({
  EVERYONE: "EVERYONE",
  STUDENT: "STUDENT",
  LECTURER: "LECTURER",
  DEAN: "DEAN",
  FACULTY_ADMIN: "FACULTY_ADMIN",
});

export const SYSTEM_ROLE_DEFAULTS = Object.freeze({
  [SYSTEM_ROLE_KEYS.EVERYONE]:
    B.VIEW_CHANNEL |
    B.READ_MESSAGE_HISTORY |
    B.SEND_MESSAGES |
    B.ATTACH_FILES |
    B.EMBED_LINKS |
    B.ADD_REACTIONS |
    B.USE_EXTERNAL_EMOJI |
    B.CREATE_THREADS |
    B.SEND_MESSAGES_IN_THREADS,
  [SYSTEM_ROLE_KEYS.STUDENT]:
    B.VIEW_CHANNEL |
    B.READ_MESSAGE_HISTORY |
    B.SEND_MESSAGES |
    B.ATTACH_FILES |
    B.EMBED_LINKS |
    B.ADD_REACTIONS |
    B.USE_EXTERNAL_EMOJI |
    B.CREATE_THREADS |
    B.SEND_MESSAGES_IN_THREADS,
  [SYSTEM_ROLE_KEYS.LECTURER]:
    B.VIEW_CHANNEL |
    B.READ_MESSAGE_HISTORY |
    B.SEND_MESSAGES |
    B.ATTACH_FILES |
    B.EMBED_LINKS |
    B.ADD_REACTIONS |
    B.USE_EXTERNAL_EMOJI |
    B.CREATE_THREADS |
    B.SEND_MESSAGES_IN_THREADS |
    B.MANAGE_MESSAGES |
    B.MANAGE_THREADS |
    B.PIN_MESSAGES |
    B.MENTION_EVERYONE,
  [SYSTEM_ROLE_KEYS.DEAN]:
    B.VIEW_CHANNEL |
    B.READ_MESSAGE_HISTORY |
    B.SEND_MESSAGES |
    B.ATTACH_FILES |
    B.EMBED_LINKS |
    B.ADD_REACTIONS |
    B.USE_EXTERNAL_EMOJI |
    B.CREATE_THREADS |
    B.SEND_MESSAGES_IN_THREADS |
    B.MANAGE_MESSAGES |
    B.MANAGE_THREADS |
    B.PIN_MESSAGES |
    B.MANAGE_CHANNEL |
    B.MANAGE_ROLES |
    B.MENTION_EVERYONE |
    B.VIEW_AUDIT_LOG |
    B.MUTE_MEMBERS |
    B.MODERATE_MEMBERS,
  [SYSTEM_ROLE_KEYS.FACULTY_ADMIN]: PERMISSION_ADMINISTRATOR,
});

/** Bits stripped when a user is outside a channel's academic scope. */
export const SCOPE_DENIED_MASK =
  B.VIEW_CHANNEL |
  B.READ_MESSAGE_HISTORY |
  B.SEND_MESSAGES |
  B.ATTACH_FILES |
  B.EMBED_LINKS |
  B.ADD_REACTIONS |
  B.USE_EXTERNAL_EMOJI |
  B.CREATE_THREADS |
  B.SEND_MESSAGES_IN_THREADS |
  B.MANAGE_MESSAGES |
  B.MANAGE_THREADS |
  B.PIN_MESSAGES |
  B.MENTION_EVERYONE;
