import { AUTH_BRAND } from '@/config/auth-brand';
import { currentUserName, escapeHtml } from './report-print-shell';
import type { ReportTabId } from './report-tabs';

const TAB_CODE: Record<ReportTabId, string> = {
  overview: 'OVW',
  enrollment: 'ENR',
  courses: 'CRS',
  communication: 'COM',
  usage: 'USE',
  students: 'STU',
  'user-logs': 'LOG',
  'teacher-activity': 'TAC',
};

const ENTITY_SCOPE_CODE: Record<string, string> = {
  course: 'CRS',
  teacher: 'TCH',
  student: 'STU',
  batch: 'BAT',
  section: 'SEC',
  faculty: 'FAC',
  class: 'CLS',
};

export type ReportInvoiceMeta = {
  documentTitle: string;
  documentSubtitle?: string;
  reportId: string;
  generatedAt: string;
  periodLabel: string;
  fromLines: string[];
  toTitle: string;
  toLines: string[];
  details?: { label: string; value: string }[];
};

function logoSrc(): string {
  if (typeof window === 'undefined') return '/assets/img/brand/sidebarlogo.png';
  return `${window.location.origin}/assets/img/brand/sidebarlogo.png`;
}

function makeReportId(prefix: string): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  const t = String(d.getHours()).padStart(2, '0') + String(d.getMinutes()).padStart(2, '0');
  return `${prefix}-${y}${m}${day}-${t}`;
}

export function facultyReportId(tab: ReportTabId = 'overview'): string {
  return makeReportId(`RPT-FAC-${TAB_CODE[tab]}`);
}

export function adminReportId(tab: ReportTabId = 'overview'): string {
  return makeReportId(`RPT-ADM-${TAB_CODE[tab]}`);
}

/** Entity-scoped reports at `/dashboard/reports`. */
export function entityReportId(
  scope: string,
  kind: 'list' | 'detail' = 'detail'
): string {
  const code = ENTITY_SCOPE_CODE[scope] ?? 'ENT';
  return makeReportId(`RPT-${code}-${kind === 'list' ? 'LST' : 'DTL'}`);
}

export function buildReportInvoiceHeader(meta: ReportInvoiceMeta): string {
  const details = meta.details ?? [];
  const subLine = [
    `Ref #: ${meta.reportId}`,
    `Period: ${meta.periodLabel}`,
    ...details.map((d) => `${d.label}: ${d.value}`)
  ].join(' · ');

  return `
<header class="rpt-head">
  <img class="rpt-logo" src="${escapeHtml(logoSrc())}" alt="${escapeHtml(AUTH_BRAND.productName)}" width="180" height="46" />
  <div class="rpt-org">${escapeHtml(AUTH_BRAND.organization)}</div>
  <div class="rpt-doc-title">${escapeHtml(meta.documentTitle)}</div>
  ${meta.documentSubtitle ? `<div class="rpt-doc-sub">${escapeHtml(meta.documentSubtitle)}</div>` : ''}
  <div class="rpt-meta">
    <span>Generated at: ${escapeHtml(meta.generatedAt)}</span>
    <span>Generated by: ${escapeHtml(currentUserName())}</span>
  </div>
  <div class="rpt-meta rpt-meta-sub">
    <span>${escapeHtml(subLine)}</span>
    <span>${escapeHtml(meta.toTitle)}</span>
  </div>
</header>
`;
}
